version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: root
